dictionary-replicator:
  tables: REF_4_1_9, REF_5_1_18
  REF_4_1_9:
    constraints: CREATE INDEX IF NOT EXISTS idx_id_4_1_9 ON REF_4_1_9(CODE, RSA_CODE)
  REF_5_1_18:
    constraints: CREATE INDEX IF NOT EXISTS idx_id_5_1_18 ON REF_5_1_18(MAP_CAR_TRANSDEKRA_ID)
  cron: "0 0 11 * * ?"
  scheduleEnabled: true
  artifactory:
    repository: dsa-release-local